app/assets/javascripts/components/StaticPages/involvement_page.es6.jsx, app/assets/stylesheets/pages/involvement.scss, app/assets/stylesheets/partials/_layouts.scss
=> Make some styling changes to involvement page

Gemfile, Gemfile.lock, app/models/admin.rb, app/models/lesson.rb, app/models/matching.rb, app/models/student.rb, app/models/teacher.rb, db/seeds.rb
@sonia-y im not really sure what validations are supposed to be like but I pattern matched so hopefully this is mostly right??
=> validations

app/assets/javascripts/components/student/components/lesson_card.es6.jsx, app/assets/javascripts/components/student/pages/student_lessons_page.es6.jsx, app/assets/javascripts/constants/api_constants.es6.jsx, app/controllers/api/students_controller.rb, app/models/lesson.rb, config/routes.rb, db/seeds.rb
=> Create RecentLessons endpoint + scope + route + render in StudentLessonPage + Add recent/upcoming seeds  

app/assets/javascripts/components/authentication/login_page.es6.jsx, app/assets/javascripts/components/form/student_form.es6.jsx, app/assets/javascripts/components/header.es6.jsx, app/assets/javascripts/components/user_header.es6.jsx, app/assets/javascripts/constants/api_constants.es6.jsx, app/assets/javascripts/constants/route_constants.es6.jsx, app/controllers/authentication/students/registrations_controller.rb, app/models/instrument.rb, app/models/student.rb, app/models/teacher.rb
also, move authentication routes to apiconstants
=> Add instruments as nested attributes to student model

app/assets/javascripts/components/student/components/student_lesson_card.es6.jsx, app/assets/javascripts/components/teacher/components/teacher_lesson_card.es6.jsx, app/assets/javascripts/helpers/constants.es6.jsx, app/serializers/lesson/lesson_show_serializer.rb, app/serializers/matching/matching_base_serializer.rb, db/seeds.rb
=> Create Matching Serializer + Render instrument on student/teacher card 

app/assets/javascripts/components/student/components/student_lesson_card.es6.jsx, app/assets/javascripts/components/teacher/components/teacher_lesson_card.es6.jsx, app/models/lesson.rb, app/serializers/lesson/lesson_base_serializer.rb, db/migrate/20161129002314_add_location_to_matchings_and_lessons.rb, db/schema.rb, db/seeds.rb, spec/factories/lessons.rb, spec/factories/teachers.rb, spec/models/lesson_spec.rb, spec/models/teacher_spec.rb
=> Create Serializer for Matching + Add location rendering for student/teacher dashboard 

app/assets/javascripts/components/form/student_form.es6.jsx, app/assets/javascripts/constants/api_constants.es6.jsx, app/assets/stylesheets/form/form.scss, app/controllers/authentication/students/registrations_controller.rb, app/controllers/stripe/accounts_controller.rb, app/controllers/stripe/charges_controller.rb, app/controllers/stripe/customers_controller.rb, app/models/student.rb
=> Created Student Form/Stripe Customer Creations

app/assets/javascripts/components/form/student_form.es6.jsx, app/assets/javascripts/components/form/teacher_form.es6.jsx
=> Added async to teacher/student forms

app/controllers/api/lessons_controller.rb, app/mailers/lesson_mailer.rb, app/models/lesson.rb, app/views/lesson_mailer/reschedule_notify_parent.html.erb, app/views/lesson_mailer/reschedule_notify_parent.text.erb, app/views/lesson_mailer/reschedule_notify_student.html.erb, app/views/lesson_mailer/reschedule_notify_student.text.erb, app/views/lesson_mailer/reschedule_notify_teacher.html.erb, app/views/lesson_mailer/reschedule_notify_teacher.text.erb
=> Send reschedule email when lesson reschedules

app/assets/javascripts/components/authentication/login_page.es6.jsx
=> allow enter key to submit login form

app/assets/javascripts/components/footer.es6.jsx, app/assets/javascripts/components/form/teacher_form.es6.jsx, app/assets/javascripts/components/form/teacher_information.es6.jsx, app/assets/javascripts/components/static/about_page.es6.jsx, app/assets/javascripts/components/static/home_page.es6.jsx, app/assets/javascripts/components/static/program_page.es6.jsx, app/assets/stylesheets/application.scss, app/assets/stylesheets/static/about.scss, app/assets/stylesheets/static/program.scss
To see comments addressed, see:
[ForteComments02.12.17.pdf](https://github.com/calblueprint/forte/files/772847/CopyofForteComments02.12.17.pdf)
visual changes:
---
=> small tweaks based on feedback

app/assets/javascripts/components/authentication/login_page.es6.jsx, app/views/authentication/admins/passwords/edit.html.erb, app/views/authentication/students/passwords/edit.html.erb, app/views/authentication/teachers/passwords/edit.html.erb
=> Stylized change password

app/assets/javascripts/components/dashboard/reschedule_modal.es6.jsx, app/controllers/api/lessons_controller.rb, app/mailers/lesson_mailer.rb, app/views/forte_mailer/student_signup_notify_admin.html.erb, app/views/forte_mailer/student_signup_notify_parent.html.erb, app/views/forte_mailer/student_signup_notify_parent.text.erb, app/views/forte_mailer/student_signup_notify_student.html.erb, app/views/forte_mailer/student_signup_notify_student.text.erb, app/views/forte_mailer/teacher_signup_notify_admin.html.erb, app/views/forte_mailer/teacher_signup_notify_teacher.html.erb, app/views/forte_mailer/teacher_signup_notify_teacher.text.erb, app/views/lesson_mailer/cancel_notify_parent.html.erb, app/views/lesson_mailer/cancel_notify_parent.text.erb, app/views/lesson_mailer/cancel_notify_student.html.erb, app/views/lesson_mailer/cancel_notify_student.text.erb, app/views/lesson_mailer/cancel_notify_teacher.html.erb, app/views/lesson_mailer/cancel_notify_teacher.text.erb, app/views/lesson_mailer/reschedule_notify_parent.html.erb, app/views/lesson_mailer/reschedule_notify_parent.text.erb, app/views/lesson_mailer/reschedule_notify_student.html.erb, app/views/lesson_mailer/reschedule_notify_student.text.erb, app/views/lesson_mailer/reschedule_notify_teacher.html.erb, app/views/lesson_mailer/reschedule_notify_teacher.text.erb, app/views/partials/_email_header.html.erb, test/mailers/previews/forte_mailer_preview.rb
fix #326 Added basic styling to emails
=> styled emails

app/assets/javascripts/components/form/student_form.es6.jsx, app/assets/javascripts/components/form/teacher_form.es6.jsx, app/models/student.rb, app/models/teacher.rb, db/migrate/20170305222102_add_placeid_to_teachers_and_students.rb, db/schema.rb, spec/factories/students.rb, spec/factories/teachers.rb, spec/models/student_spec.rb, spec/models/teacher_spec.rb
=> adding placeid field to teachers and students

app/assets/javascripts/components/form/student_form.es6.jsx, app/assets/javascripts/components/form/waiver_modal.es6.jsx
=> added waiver text

app/assets/javascripts/components/form/teacher_form.es6.jsx, app/assets/javascripts/components/form/waiver_modal.es6.jsx, app/controllers/api/teachers_controller.rb, app/controllers/authentication/teachers/registrations_controller.rb, app/models/teacher.rb, db/migrate/20170312010120_alter_column_is_searching_to_add_teach_for_free_to_teachers.rb, db/schema.rb, db/seeds.rb, spec/factories/teachers.rb, spec/models/teacher_spec.rb
=> added teach for free features

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/components/admin/matchings_components/full_student.es6.jsx, app/assets/javascripts/components/admin/matchings_components/full_teacher.es6.jsx, app/assets/javascripts/components/admin/matchings_components/matching_modal.es6.jsx, app/assets/javascripts/components/admin/unmatched_page.es6.jsx, app/assets/javascripts/components/calendars/matching_calendar.es6.jsx, app/assets/javascripts/components/form/student_form.es6.jsx, app/assets/javascripts/components/form/teacher_form.es6.jsx, app/assets/javascripts/helpers/calendar_helper.es6.jsx, app/controllers/api/teachers_controller.rb, app/controllers/authentication/students/registrations_controller.rb, app/controllers/authentication/teachers/registrations_controller.rb, app/models/student.rb, app/models/teacher.rb, app/serializers/student/student_show_serializer.rb, app/serializers/teacher/teacher_show_serializer.rb, config/initializers/timezone.rb, db/migrate/20170310041723_add_lat_lng_timezone_to_teachers_and_students.rb, db/schema.rb, db/seeds.rb, spec/factories/students.rb, spec/factories/teachers.rb, spec/models/student_spec.rb, spec/models/teacher_spec.rb
Teacher form and student form use either autocomplete or geocoder to get a lat/lng corresponding to the user's location. On submit the backend fetches the corresponding timezone using the timezone gem. 
Note: haven't updating the matching modal yet to reflect the correct timezone.
=> timezone and lat/lon correctly put into database on form submit 

app/assets/javascripts/components/admin/matchings_components/matching_modal.es6.jsx
=> matching times can now be 30-60 minutes long

app/assets/javascripts/components/dashboard/lesson_card.es6.jsx
=> Fixed floating precision

app/assets/javascripts/components/common/editable_input.es6.jsx, app/assets/javascripts/components/common/editable_input_group.es6.jsx, app/assets/javascripts/components/common/user_settings.es6.jsx, app/assets/javascripts/components/format_input_helper.es6.jsx, app/assets/javascripts/components/student/student_settings_page.es6.jsx
fixing saving bug on settings page
=> settings page bug fixes

app/assets/javascripts/components/form/teacher_form.es6.jsx, app/assets/javascripts/components/format_input_helper.es6.jsx
=> Added date and phone input formatting for teachers

app/assets/javascripts/components/autocomplete/address_form.es6.jsx
=> Hotfix Address Component
